import express from 'express';
import  {getMoviesList,addMovies,getFeaturedMovies,getMoviesBySearch,getPopularMovies,updateMovie,deleteMovie}  from '../controllers/movies.js';
import auth from '../middleware/auth.js';
const router = express.Router();
router.get('/watchlist',auth, getMoviesList);
router.get('/featured',getFeaturedMovies);
router.get('/search',getMoviesBySearch);
router.get('/popular',getPopularMovies);
router.post('/',auth,addMovies);
router.patch('/',auth,updateMovie);
router.delete('/',auth,deleteMovie);
export default router;